name = "tellmedo-freemail"
main = "src/server.js"
compatibility_date = "2024-01-01"
keep_vars = true

[vars]
MAIL_DOMAIN = "gmail.tellmedo.org,icloud.tellmedo.org,live.tellmedo.org,apple.tellmedo.org,edu.tellmedo.org,nvidia.tellmedo.org,doii.ai,gmail.doii.ai,icloud.doii.ai,live.doii.ai,apple.doii.ai,edu.doii.ai,nvidia.doii.ai,nexddcc.ccwu.cc,xaii.ccwu.cc,xaai.ccwu.cc,xaii.cc.cd"

[[d1_databases]]
binding = "TEMP_MAIL_DB"
database_name = "mail_free_db"
database_id = "3b167217-781e-4c79-ab34-5a59fb1e9385"

[assets]
directory = "public"
binding = "ASSETS"

[[r2_buckets]]
binding = "MAIL_EML"
bucket_name = "mail-eml"
